apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: backend
  namespace: default
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`backend.localhost`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: backend
      port: 80

